DROP TABLE IF EXISTS ODONTOLOGOS;
                CREATE TABLE ODONTOLOGOS (
                MATRICULA INT PRIMARY KEY,
                NOMBRE VARCHAR(255) NOT NULL,
                APELLIDO VARCHAR(255) NOT NULL);